
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_training'
version: '1.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

packages-install-path: "dbt_packages"

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# query-comment: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success"
#   append: true

query-comment: 
  comment: "{{ query_comment(node) }}"
  append: True

require-dbt-version: [">=1.0.0","<2.0.0"]

flags:
  debug: true

dbt-cloud:
  project-id: 311005

quoting:
  database: true
  schema: true
  identifier: true

tests:
  +group: finance

models:
  +persist_docs:
    relation: true
    columns: true
  +materialized: table
  +group: finance
  marts:
    +tags:
        - "hourly"
        - "published"
    core:
      +materialized: table
  staging:
    +materialized: view
    +tags:
        - "daily"
    jaffle_Shop:
      +tags:
        - "daily"
  metrics:
    +tags:
        - "daily"
        - "published"